# 敏感词库配置
# 注意：实际使用时应该使用专业的敏感词库

categories:
  # 政治敏感
  political:
    name: "政治敏感"
    weight: 1.0
    enabled: true
    words:
      # 领导人相关
      - "习近平"
      - "xjp"
      - "x j p"
      - "cxjp"
      - "c xjp"
      - "打倒习近平"
      - "打倒xjp"
      - "打 倒 x j p"
      - "打倒 xjp"
      - "反对习近平"
      - "反对xjp"
      # 同音字和表情符号变形
      - "习近平猪"
      - "习近平🐷"
      - "习🐷"
      - "习大大🐷"
      - "包子"
      - "维尼"
      - "小熊维尼"
      - "🐻"
      - "熊包子"
      - "猪头"
      - "🐼"
      - "下台"
      - "推翻"
      - "打倒"
      - "颠覆"
      - "反华"
      - "反党"
      - "反政府"
      - "民运"
      - "六四"
      - "89"
      - "天安门"
      - "法轮功"
      - "台独"
      - "藏独"
      - "疆独"
      - "港独"
      - "分裂"
      - "独立"
      - "反动"
      - "敌对势力"
      - "境外势力"
      - "颜色革命"
      - "政变"
      - "起义"
      - "暴动"
      - "革命"
      - "抗议"
      - "示威"
      - "游行"
      - "罢工"
      - "维权"
      - "民主"
      - "自由"
      - "人权"
      - "专制"
      - "独裁"
      - "威权"
      - "集权"
      - "一党专政"
      - "共产党"
      - "ccp"
      - "中共"
      - "tg"
      - "土共"
      - "匪帮"
      - "邪恶"
      - "腐败"
      - "贪污"
      - "腐朽"
      - "黑暗"
      - "残暴"
      - "暴政"
      - "压迫"
      - "迫害"
      - "镇压"
      - "封锁"
      - "审查"
      - "洗脑"
      - "愚民"
      - "奴役"
      
  # 暴力内容
  violence:
    name: "暴力内容"
    weight: 0.9
    enabled: true
    words:
      - "暴力"
      - "恐怖"
      - "威胁"
      - "伤害"
      - "攻击"
      - "杀死"
      - "杀害"
      - "谋杀"
      - "自杀"
      - "恐怖主义"
      - "炸弹"
      - "爆炸"
      - "枪击"
      - "屠杀"
      - "血腥"
      - "残忍"
      - "酷刑"
      - "折磨"
      - "虐待"
      - "殴打"
      - "砍杀"
      - "刺杀"
      - "暗杀"
      - "行刺"
      - "袭击"
      - "报复"
      - "仇杀"
      - "灭口"
      
  # 违法内容
  illegal:
    name: "违法内容" 
    weight: 1.0
    enabled: true
    words:
      - "毒品"
      - "走私"
      - "诈骗"
      - "洗钱"
      - "贩卖"
      - "贩毒"
      - "制毒"
      - "吸毒"
      - "大麻"
      - "海洛因"
      - "冰毒"
      - "摇头丸"
      - "可卡因"
      - "鸦片"
      - "吗啡"
      - "麻醉品"
      - "精神药品"
      - "假币"
      - "伪造"
      - "仿制"
      - "盗版"
      - "侵权"
      - "窃取"
      - "盗窃"
      - "抢劫"
      - "绑架"
      - "勒索"
      - "敲诈"
      - "贿赂"
      - "受贿"
      - "行贿"
      - "偷税"
      - "漏税"
      - "逃税"
      - "避税"
      
  # 成人内容
  adult:
    name: "成人内容"
    weight: 0.8
    enabled: true
    words:
      - "色情"
      - "淫秽"
      - "裸体"
      - "性交"
      - "做爱"
      - "性爱"
      - "性行为"
      - "性器官"
      - "阴茎"
      - "阴道"
      - "乳房"
      - "胸部"
      - "臀部"
      - "生殖器"
      - "私处"
      - "激情"
      - "诱惑"
      - "勾引"
      - "调情"
      - "挑逗"
      - "性感"
      - "骚"
      - "浪"
      - "骚货"
      - "妓女"
      - "娼妇"
      - "嫖娼"
      - "卖淫"
      - "援交"
      - "包养"
      - "一夜情"
      - "约炮"
      - "3P"
      - "群P"
      
  # 仇恨言论
  hate_speech:
    name: "仇恨言论"
    weight: 0.7
    enabled: true
    words:
      - "歧视"
      - "仇恨"
      - "侮辱"
      - "种族歧视"
      - "性别歧视"
      - "地域歧视"
      - "民族歧视"
      - "宗教歧视"
      - "恶毒"
      - "恶意"
      - "恶心"
      - "讨厌"
      - "厌恶"
      - "鄙视"
      - "蔑视"
      - "轻视"
      - "低贱"
      - "下等"
      - "劣等"
      - "垃圾"
      - "废物"
      - "人渣"
      - "败类"
      - "畜生"
      - "禽兽"
      - "狗"
      - "猪"
      - "傻逼"
      - "白痴"
      - "智障"
      - "弱智"
      - "残废"
      
  # 虚假信息
  misinformation:
    name: "虚假信息"
    weight: 0.6
    enabled: true
    words:
      - "谣言"
      - "假消息"
      - "虚假宣传"
      - "造谣"
      - "传谣"
      - "辟谣"
      - "假新闻"
      - "不实消息"
      - "误导"
      - "欺骗"
      - "虚假"
      - "伪造"
      - "编造"
      - "捏造"
      - "杜撰"
      - "夸大"
      - "歪曲"
      - "篡改"
      - "抹黑"
      - "污蔑"
      - "诽谤"
      - "中伤"
      
  # 垃圾信息
  spam:
    name: "垃圾信息"
    weight: 0.4
    enabled: true
    words:
      - "刷单"
      - "代办"
      - "加微信"
      - "免费领取"
      - "赚钱"
      - "兼职"
      - "招聘"
      - "代理"
      - "加盟"
      - "投资"
      - "理财"
      - "股票"
      - "期货"
      - "基金"
      - "保险"
      - "贷款"
      - "借钱"
      - "放贷"
      - "高利贷"
      - "套现"
      - "提现"
      - "返利"
      - "返现"
      - "优惠"
      - "折扣"
      - "促销"
      - "特价"
      - "限时"
      - "抢购"
      - "秒杀"
      - "团购"
      - "拼团"
      
  # 骚扰内容
  harassment:
    name: "骚扰内容"
    weight: 0.6
    enabled: true
    words:
      - "骚扰"
      - "威胁"
      - "恶意"
      - "恐吓"
      - "跟踪"
      - "纠缠"
      - "烦扰"
      - "干扰"
      - "滋扰"
      - "挑衅"
      - "找茬"
      - "找麻烦"
      - "报复"
      - "算账"
      - "清算"
      - "秋后算账"
      - "人身攻击"
      - "网络暴力"
      - "网暴"
      - "人肉"
      - "爆料"
      - "举报"
      
  # 诈骗信息
  fraud:
    name: "诈骗信息"
    weight: 0.9
    enabled: true
    words:
      - "诈骗"
      - "套路贷"
      - "刷单赚钱"
      - "投资理财"
      - "高回报"
      - "零风险"
      - "稳赚不赔"
      - "日赚千元"
      - "轻松赚钱"
      - "躺赚"
      - "被动收入"
      - "一夜暴富"
      - "发财致富"
      - "中奖"
      - "彩票"
      - "赌博"
      - "博彩"
      - "赌场"
      - "押注"
      - "下注"
      - "竞猜"
      - "预测"
      - "内幕消息"
      - "小道消息"
      - "内部信息"
      - "黑幕"
      - "潜规则"

# 白名单词汇（不会被标记为敏感）
whitelist:
  - "正当竞争"
  - "合法权益"
  - "正常讨论"
  - "新华社"
  - "人民日报"
  - "央视"
  - "官方"
  - "政府"
  - "国家"
  - "党"
  - "领导"
  - "政策"
  - "法规"
  - "会议"
  - "报告"
  - "讲话"
  - "指示"
  - "通知"
  - "公告"
  - "声明"

# 敏感词匹配配置
matching:
  # 是否启用模糊匹配
  fuzzy_matching: true
  
  # 是否忽略大小写
  ignore_case: true
  
  # 是否忽略空格和标点
  ignore_punctuation: true
  
  # 最小匹配长度
  min_length: 2
  
  # 相似度阈值（用于模糊匹配）
  similarity_threshold: 0.8

# 动态更新配置
update:
  # 是否启用热更新
  hot_reload: true
  
  # 更新检查间隔（秒）
  check_interval: 300
  
  # 外部词库API
  external_api:
    enabled: false
    url: ""
    api_key: ""
    update_interval: 3600 